### ISSUE TITLE
12_react_server_side_rendering fails to runs

### ISSUE THREAD

**Issue by bresson** [PacktPublishing/Node.js_Design_Patterns_Second_Edition_Code#1]
For the section above in chapter 8, the book states use "node server" to start the server. 

The source code readme , however, states "you need to run the server using babel-cli: 'node_modules/.bin/babel-cli server.js'"

Neither of them work and both return the following error: "let markup = ReactDom.renderToString(<Router.RouterContext {...renderProps} />);   

SyntaxError: Unexpected token <  "

**Comment by lmammino** [comment]
Hello @bresson,
`babel-cli` has been renamed `babel-node` so the correct command is:

```bash
node_modules/.bin/babel-node server.js
```

This has been fixed in fac8126dc108006d66b1228bbd275fe1fd3cdb98

Thanks for finding this issue 👍
