### ISSUE TITLE
Comment says that var is intentionally being used but it is not. Const is used which throws an error.

### ISSUE THREAD

**Issue by ar5had** [PacktPublishing/Node.js_Design_Patterns_Second_Edition_Code#10]
https://github.com/PacktPublishing/Node.js_Design_Patterns_Second_Edition_Code/blob/af9158c2ff5aefeca334f50a6302c0f01b7ce2f5/Chapter02/10_module_loader/loader.js#L15

**Comment by sonam-packt** [comment]
Please reopen the issue if still exist, thank you
