### ISSUE TITLE
Adding images

### ISSUE THREAD

**Issue by praju89** [PacktPublishing/Node.js_Design_Patterns_Second_Edition_Code#12]
![nodejsgithub](https://user-images.githubusercontent.com/12148709/36580590-e1304a68-188e-11e8-8df3-a3c38ad1cc8c.PNG)

![image](https://user-images.githubusercontent.com/12148709/36580840-f9f61770-188f-11e8-9bb4-ea8dc1686ff5.png)

![image](https://user-images.githubusercontent.com/12148709/36580846-fdd5aa54-188f-11e8-85b0-8591de71459e.png)

![image](https://user-images.githubusercontent.com/12148709/36581298-3ed2535c-1892-11e8-9021-394020c1cc20.png)

**Comment by lmammino** [comment]
Hello @praju89, can you do a PR (pull request) so that we can understand were do you think those images should be added?

Thanks
