### ISSUE TITLE
Chapter 8 / module 14

### ISSUE THREAD

**Issue by bresson** [PacktPublishing/Node.js_Design_Patterns_Second_Edition_Code#2]
When I start the API and web server, both start without issue. However, when I navigate a browser to localhost:300, the terminal responds with "TypeError: loadPropsOnServer is not a function."

When I remove .default from require('async-props').default and run both the API and web server, then navigate the browser to that page, the page hangs and here is a response in the web server terminal:

Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).

Any clues?

**Comment by lmammino** [comment]
Hello @bresson,
Thanks for finding out this issue.

The `loadPropsOnServer` function was not imported correctly from the module. In the current version it is now fixed as well with some other minor fixes/improvements.
