### ISSUE TITLE
bug in example 06_web_spider_v4 

### ISSUE THREAD

**Issue by loohoo** [PacktPublishing/Node.js_Design_Patterns_Second_Edition_Code#22]
call spider function with nesting large than 1 would't work as expected
![757x 7 8ke3z at 0 j3](https://user-images.githubusercontent.com/7367421/51829988-c0fdca80-2329-11e9-9704-801a55ff399a.png)

![93rep076 e2n a3b as nv](https://user-images.githubusercontent.com/7367421/51830068-eee30f00-2329-11e9-85a9-67b0bc94bf12.png)
only two page had been download. and the callback never been call

**Comment by zhouitpro** [comment]
Hi loohoo. 
the question is done() function not to callback.  the taskQueue running-- no run.

to fix. i have add one line to run callback.

![image](https://user-images.githubusercontent.com/342575/52997737-59382c80-345c-11e9-9c68-97665e7a4d67.png)

**Comment by loohoo** [comment]
感谢

**Comment by ljf0113** [comment]
@zhouitpro  It may still have a bug.Callback run too many times~
