### ISSUE TITLE
node_modules/authsrv-plugin-logout mentioned in chapter 07 example 05_plugin_module_impersonation does not exist

### ISSUE THREAD

**Issue by Cuneytt** [PacktPublishing/Node.js_Design_Patterns_Second_Edition_Code#6]
node_modules/authsrv-plugin-logout mentioned in chapter 07 example 05_plugin_module_impersonation does not exist

**Comment by steven0129** [comment]
Same issue

**Comment by ashokduddukuri** [comment]
@lmammino I'm facing the same issue. There is no package published to npm with the name authsrv-plugin-logout

```
➜  NOde npm search authsrv-plugin-logout
No matches found for "authsrv-plugin-logout"

```

Creating a package and publishing to npm should solve this. Lemme know if i can take this up.

**Comment by sarvesh-packt** [comment]
Please reopen if the issue still persists.
