### ISSUE TITLE
Chapter03/04_web_spider_v2

### ISSUE THREAD

**Issue by chellitorvic** [PacktPublishing/Node.js_Design_Patterns_Second_Edition_Code#9]
The `spiderLinks` function is supposed to be asynchronous, but it seems that the `callback` will be executed synchronously in case `utilities.getPageLinks(currentUrl, body)` returns an empty array.

**Comment by sohamapackt** [comment]
Hi,

I am closing the issue.
If the problem still persists, feel free to reopen it.

Thanks!
